version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: resume_optimizer_backend
    ports:
      - "8002:8002"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - resume_db:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8002

  frontend:
    build:
      context: ./frontend
    container_name: resume_optimizer_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  resume_db:
