
import json
from fpdf import FPDF

def normalize_text(text: str) -> str:
    if not text: return ""
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "-",
        "\u2026": "...",
        "\u2022": "-",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text.encode('latin-1', 'replace').decode('latin-1')

class PDFGenerator(FPDF):
    def header(self): pass
    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, normalize_text(f"Generated by AI Resume Optimizer - Page {self.page_no()}"), align="C")

    def add_section(self, title):
        self.set_font("helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, normalize_text(title.upper()), ln=True, fill=True)
        self.ln(2)

    def generate_resume_pdf(self, content):
        self.add_page()
        self.set_font("helvetica", "B", 20)
        self.cell(0, 10, normalize_text(content.get("full_name", "Resume")), ln=True, align="C")
        
        self.set_font("helvetica", "", 9)
        contact = content.get("contact", {})
        contact_str = f"{contact.get('email')} | {contact.get('phone')} | {contact.get('location')}"
        self.cell(0, 5, normalize_text(contact_str), ln=True, align="C")
        
        self.ln(5)
        if content.get("experience"):
            self.add_section("Professional Experience")
            for exp in content.get("experience"):
                self.set_font("helvetica", "B", 10)
                left_text = normalize_text(f"{exp.get('role')} at {exp.get('company')}")
                # TEST: If left_text is very long, it might trigger the error if cell width is fixed
                print(f"Testing experience: {left_text}")
                self.cell(140, 5, left_text, ln=False)
                self.set_font("helvetica", "I", 9)
                self.cell(0, 5, normalize_text(exp.get("duration")), ln=True, align="R")
                self.ln(3)

        return self.output()

test_content = {
    "full_name": "Test User",
    "contact": {"email": "test@example.com", "phone": "1234567890", "location": "City, Country"},
    "experience": [
        {
            "role": "Very Long Role Name that Might Exceed the 140 width limit if the font size or character count is too high and triggers the FPDF break",
            "company": "Very Long Company Name International Global Solutions and Services",
            "duration": "2021 - Present"
        }
    ]
}

try:
    gen = PDFGenerator()
    gen.generate_resume_pdf(test_content)
    print("PDF Generated successfully in test script")
except Exception as e:
    print(f"Caught error: {e}")
