import os
import json
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import fitz  # PyMuPDF
from pydantic import BaseModel
from dotenv import load_dotenv
import sqlite3
from datetime import datetime
from fpdf import FPDF
import io
from fastapi.responses import StreamingResponse

load_dotenv()

def normalize_text(text: str) -> str:
    """Replace common Unicode characters that break standard PDF fonts with ASCII equivalents."""
    if not text: return ""
    replacements = {
        "\u2018": "'", "\u2019": "'",  # Smart single quotes
        "\u201c": '"', "\u201d": '"',  # Smart double quotes
        "\u2013": "-", "\u2014": "-",  # En and em dashes
        "\u2026": "...",              # Ellipses
        "\u2022": "-",                # Bullet points
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Fallback: remove any other non-latin1 characters to prevent crash
    return text.encode('latin-1', 'replace').decode('latin-1')

class PDFGenerator(FPDF):
    def header(self):
        # We handle header manually in content to allow dynamic positioning
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, normalize_text(f"Generated by AI Resume Optimizer - Page {self.page_no()}"), align="C")

    def add_section(self, title):
        self.set_font("helvetica", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, normalize_text(title.upper()), ln=True, fill=True)
        self.ln(2)

    def generate_resume_pdf(self, content):
        self.add_page()
        
        # Header - Centered
        self.set_font("helvetica", "B", 20)
        self.cell(0, 10, normalize_text(content.get("full_name", "Resume")), ln=True, align="C")
        
        self.set_font("helvetica", "", 9)
        contact = content.get("contact", {})
        contact_str = f"{contact.get('email')} | {contact.get('phone')} | {contact.get('location')}"
        self.cell(0, 5, normalize_text(contact_str), ln=True, align="C")
        
        links = []
        if contact.get("linkedin"): links.append(contact.get("linkedin"))
        if contact.get("github"): links.append(contact.get("github"))
        if links:
            self.cell(0, 5, normalize_text(" | ".join(links)), ln=True, align="C")
        
        self.ln(5)

        # Summary
        if content.get("summary"):
            self.add_section("Professional Summary")
            self.set_font("helvetica", "", 10)
            self.multi_cell(0, 5, normalize_text(content.get("summary")))
            self.ln(5)

        # Experience
        if content.get("experience"):
            self.add_section("Professional Experience")
            for exp in content.get("experience"):
                # Sequential layout to prevent horizontal space issues
                self.set_font("helvetica", "B", 10)
                role_company = f"{exp.get('role')} at {exp.get('company')}"
                self.multi_cell(0, 5, normalize_text(role_company))
                
                self.set_font("helvetica", "I", 9)
                self.cell(0, 5, normalize_text(exp.get("duration")), ln=True, align="R")
                
                self.set_font("helvetica", "", 9)
                for pt in exp.get("points", []):
                    self.multi_cell(0, 7, normalize_text(f"\u2022 {pt}"))
                self.ln(3)

        # Projects
        if content.get("projects"):
            self.add_section("Key Projects")
            for proj in content.get("projects"):
                self.set_font("helvetica", "B", 10)
                self.multi_cell(0, 5, normalize_text(f"{proj.get('title')} ({proj.get('tech')})"))
                
                self.set_font("helvetica", "", 9)
                for pt in proj.get("points", []):
                    self.multi_cell(0, 7, normalize_text(f"\u2022 {pt}"))
                self.ln(3)

        # Skills
        if content.get("skills"):
            self.add_section("Technical Skills")
            self.set_font("helvetica", "", 10)
            skills = content.get("skills", {})
            if skills.get('languages'): self.multi_cell(0, 6, normalize_text(f"Languages: {', '.join(skills.get('languages', []))}"))
            if skills.get('frameworks'): self.multi_cell(0, 6, normalize_text(f"Frameworks: {', '.join(skills.get('frameworks', []))}"))
            if skills.get('tools'): self.multi_cell(0, 6, normalize_text(f"Tools: {', '.join(skills.get('tools', []))}"))
            self.ln(5)

        # Keywords Added (for ATS impact visibility)
        if content.get("added_keywords"):
            self.add_section("Optimized Keywords")
            self.set_font("helvetica", "I", 9)
            self.multi_cell(0, 5, normalize_text(", ".join(content.get("added_keywords", []))))
            self.ln(5)

        # Education
        if content.get("education"):
            self.add_section("Education")
            for edu in content.get("education"):
                self.set_font("helvetica", "B", 10)
                self.multi_cell(0, 5, normalize_text(edu.get("institution")))
                
                self.set_font("helvetica", "I", 9)
                self.cell(0, 5, normalize_text(edu.get("duration")), ln=True, align="R")
                
                self.set_font("helvetica", "", 9)
                self.multi_cell(0, 5, normalize_text(edu.get("degree")))
                if edu.get("details"):
                    self.multi_cell(0, 5, normalize_text(edu.get("details")))
                self.ln(3)

        return self.output(dest="S")

app = FastAPI(title="AI Resume Optimizer API")

# Database Setup
DB_PATH = "resume_history.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp DATETIME,
            job_description TEXT,
            match_score_genai INTEGER,
            match_score_backend INTEGER,
            data_json TEXT
        )
    ''')
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS defaults (
            id TEXT PRIMARY KEY,
            filename TEXT,
            text_content TEXT
        )
    ''')
    conn.commit()
    conn.close()

init_db()

@app.post("/api/save-defaults")
async def save_defaults(
    resume_genai: UploadFile = File(None),
    resume_backend: UploadFile = File(None)
):
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        if resume_genai:
            content = extract_text_from_pdf(await resume_genai.read())
            cursor.execute("INSERT OR REPLACE INTO defaults (id, filename, text_content) VALUES ('genai', ?, ?)", 
                           (resume_genai.filename, content))
        
        if resume_backend:
            content = extract_text_from_pdf(await resume_backend.read())
            cursor.execute("INSERT OR REPLACE INTO defaults (id, filename, text_content) VALUES ('backend', ?, ?)", 
                           (resume_backend.filename, content))
        
        conn.commit()
        conn.close()
        return {"status": "success"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/get-defaults")
async def get_defaults():
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("SELECT id, filename FROM defaults")
        rows = cursor.fetchall()
        conn.close()
        return {row[0]: row[1] for row in rows}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Allow all origins for dev
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def extract_text_from_pdf(file_bytes: bytes) -> str:
    try:
        doc = fitz.open(stream=file_bytes, filetype="pdf")
        text = ""
        for page in doc:
            text += page.get_text()
        return text
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to read PDF: {str(e)}")

# Define the Pydantic schema for the LLM output is not strictly necessary since
# we can just use JSON mode or rely on the system prompt and parse it.
# We'll use the prompt directly to get strict JSON.

SYSTEM_PROMPT = """You are an expert ATS Resume Optimizer and Tech Career Coach.

The user will provide:
1. Two original resumes extracted from PDFs.
2. A job description / vacancy post.

Your goal:
- Analyze the resumes against the job description.
- Generate a highly optimized version of EACH resume (Gen AI and Backend) with a 90-100% keyword match for the given role.
- Focus on ATS readability: Use clear hierarchies, standard headings, and impactful action verbs.
- The graduation dates MUST remain exactly as "2021 - 2025".
- Suggest 2 specific Gen AI / Backend projects to build for this exact JD.
- Write a professional Cover Letter and Recruitment Email for each.

Respond ONLY with a valid JSON object. Use this exact structure:
{
  "resume_genai": {
    "match_score": number,
    "content": {
      "full_name": "string",
      "contact": { "email": "string", "phone": "string", "location": "string", "linkedin": "string", "github": "string" },
      "summary": "string focused on JD keywords",
      "education": [{ "institution": "string", "degree": "string", "duration": "2021 - 2025", "details": "string" }],
      "experience": [{ "company": "string", "role": "string", "duration": "string", "points": ["bullet point 1", "bullet point 2"] }],
      "projects": [{ "title": "string", "tech": "string", "points": ["bullet point 1"] }],
      "skills": { "languages": ["string"], "frameworks": ["string"], "tools": ["string"] }
    },
    "added_keywords": ["string"],
    "removed_keywords": ["string"],
    "ats_tips": ["string"],
    "project_suggestions": [{ "title": "string", "description": "string", "why_selected": "string" }],
    "cover_letter": "string",
    "application_email": "string"
  },
  "resume_backend": {
    "match_score": number,
    "content": {
      "full_name": "string",
      "contact": { "email": "string", "phone": "string", "location": "string", "linkedin": "string", "github": "string" },
      "summary": "string",
      "education": [{ "institution": "string", "degree": "string", "duration": "2021 - 2025", "details": "string" }],
      "experience": [{ "company": "string", "role": "string", "duration": "string", "points": ["bullet pt"] }],
      "projects": [{ "title": "string", "tech": "string", "points": ["bullet pt"] }],
      "skills": { "languages": [], "frameworks": [], "tools": [] }
    },
    "added_keywords": [],
    "removed_keywords": [],
    "ats_tips": [],
    "project_suggestions": [],
    "cover_letter": "string",
    "application_email": "string"
  }
}
"""

@app.post("/api/optimize")
async def optimize_resumes(
    resume_genai: UploadFile = File(None),
    resume_backend: UploadFile = File(None),
    job_description: str = Form(...)
):
    # Ensure Groq Token is set
    groq_api_key = os.environ.get("GROQ_API_KEY")
    if not groq_api_key:
        raise HTTPException(status_code=500, detail="GROQ_API_KEY is not set in .env")
        
    # Extract text or fetch defaults
    genai_text = ""
    backend_text = ""
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Gen AI Resume logic
    if resume_genai:
        if not resume_genai.filename.lower().endswith(".pdf"):
            raise HTTPException(status_code=400, detail="Gen AI resume must be a PDF file.")
        genai_text = extract_text_from_pdf(await resume_genai.read())
    else:
        cursor.execute("SELECT text_content FROM defaults WHERE id = 'genai'")
        row = cursor.fetchone()
        if row:
            genai_text = row[0]
        else:
            raise HTTPException(status_code=400, detail="Gen AI Resume missing and no default found.")

    # Backend Resume logic
    if resume_backend:
        if not resume_backend.filename.lower().endswith(".pdf"):
            raise HTTPException(status_code=400, detail="Backend resume must be a PDF file.")
        backend_text = extract_text_from_pdf(await resume_backend.read())
    else:
        cursor.execute("SELECT text_content FROM defaults WHERE id = 'backend'")
        row = cursor.fetchone()
        if row:
            backend_text = row[0]
        else:
            raise HTTPException(status_code=400, detail="Backend Resume missing and no default found.")
    
    conn.close()

    # Format the prompt
    user_message = f"""Inputs for optimization:

--- Original Gen AI Resume Text ---
{genai_text}

--- Original Backend Resume Text ---
{backend_text}

--- Job Description ---
{job_description}
"""
    
    from groq import Groq
    
    try:
        client = Groq(api_key=groq_api_key)
        
        # Using Llama 3 70B on Groq which supports incredibly fast token generation and JSON schema
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT + "\n\nIMPORTANT: Your entire response must be a single raw JSON object. No markdown, no backticks, no explanation. Start with { and end with }."},
                {"role": "user", "content": user_message}
            ],
            max_tokens=8000,
            temperature=0.1,
            response_format={"type": "json_object"}
        )
        
        content = response.choices[0].message.content.strip()

        # Clean up possible markdown wrappers if the model hallucinated any
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]
            
        content = content.strip()
        parsed_json = json.loads(content)

        # Save to DB
        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO history (timestamp, job_description, match_score_genai, match_score_backend, data_json)
                VALUES (?, ?, ?, ?, ?)
            ''', (
                datetime.now().isoformat(),
                job_description,
                parsed_json.get("resume_genai", {}).get("match_score", 0),
                parsed_json.get("resume_backend", {}).get("match_score", 0),
                content
            ))
            conn.commit()
            conn.close()
        except Exception as db_err:
            print(f"Database error: {db_err}")

        # Try to parse to validate it's proper JSON before returning to standard
        return parsed_json

    except json.JSONDecodeError as decode_err:
        raise HTTPException(status_code=500, detail=f"LLM returned invalid JSON. Raw output: {content}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"LLM Processing Failed: {str(e)}")

@app.get("/api/history")
async def get_history():
    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM history ORDER BY timestamp DESC LIMIT 20")
        rows = cursor.fetchall()
        conn.close()
        
        result = []
        for row in rows:
            result.append({
                "id": row["id"],
                "timestamp": row["timestamp"],
                "job_description": row["job_description"],
                "match_score_genai": row["match_score_genai"],
                "match_score_backend": row["match_score_backend"],
                "data": json.loads(row["data_json"])
            })
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch history: {str(e)}")

@app.post("/api/generate-pdf")
async def generate_pdf(request: dict):
    # 'request' will contain the 'content' object from our LLM response
    try:
        generator = PDFGenerator()
        pdf_bytes = generator.generate_resume_pdf(request)
        
        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={request.get('full_name', 'Resume').replace(' ', '_')}_Optimized.pdf"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF Generation Failed: {str(e)}")

@app.get("/health")
def health_check():
    return {"status": "ok"}
